### ISSUE TITLE
Nice work Philipp! You saved my day!

### ISSUE THREAD

**Issue by s1ntoneli** [pd95/SwiftUI-macos-HandleWindow#1]
This feels amazing! I discovered your playground at the end of a day of torment and successfully solved my problem! Thank you so much, Philipp!
However, I couldn't find a donation link. If you have one, I would love to buy you a cup of coffee to show my gratitude.

Also, I want to point out that your code is great. I think I will check out your other projects to help me learn.

-----
这感觉太棒了，在我被折磨了一天的结尾发现了你的playground，并且顺利地解决了我的问题！非常感谢你 Philipp！
不过我没有找到捐赠链接，如果你有，我很愿意请你喝一杯咖啡以表达感谢。

另外要特别提出，你的代码写的很棒，我想我会看看你的其它项目，帮助我学习一下。

**Comment by pd95** [comment]
Thanks, for the nice feedback. I'm also constantly learning SwiftUI (since iOS 13) and had to solve "strange problems", find workarounds. The "macOS window problem" took really some time to be properly solved, and I made an effort to have a "nice API" in the end. So I'm glad that it is useful to others too.

I don't have any GitHub sponsoring setup but created a "buy me a coffee" account (https://www.buymeacoffee.com/pd95), 
if you like to make a donation. I'm really trying to share my knowledge as good as possible with other learners like you.

If you want to see some of my other work, you can checkout [my stack overflow answers](https://stackoverflow.com/users/6238009/pd95?tab=answers&sort=newest).

**Comment by s1ntoneli** [comment]
Sharing is always a good thing to most people, and I hope to follow in your footsteps.
I will checkout your sof answers, I saw you "[top 5% this year](https://stackexchange.com/leagues/1/year/stackoverflow/2023-01-01/6238009#6238009)" wow!! 牛逼!!

Thanks again and enjoy the coffee.

OOh, want to say keep in touch, followed you on twitter, I'm s1ntone.
